import { SearchBar } from "./SearchBar.js";
import { TopBar } from "./topBar.js";
import { DayTemp } from "./DayTemp.js";
import { WidgetFinal } from "./WidgetFinal.js";
import { CategoryCard } from "./CategoryCard.js";
import { SocialButton } from "./socialButton.js";
import { Privacy } from "./privacyContainer.js";
import { MenuLeft } from "./menuLeft.js";
import { Test } from "./test.js";
import { OrizontalComponent } from "./OrizontalComponent.js";
import { OrizontalMenu } from "./OrizontalMenu.js";
import { NewsComponent } from "./News-Component.js";
import { SmallNews } from "./Small-News-Comp.js";
import { BreakingNews } from "./BreakingNews.js";
import { GazetaComponent } from "./gazeta.js";
import { NewsHeadline } from "./NewsHeadline.js";
import { DonatePopUp } from "./donatePopUp.js";
import { Tag } from "./tagComponent.js";
import { TagContainer } from "./tagContainer.js";
import { NewsLetter } from "./NewsLetter.js";
import { PopupSource } from "./Popup-source.js";
import { Popup } from "./popup.js";
import { Test2 } from "./test2.js";
// import { ProgramAcordeon } from "./filme/ProgramAcordeon.js";

customElements.define("search-bar", SearchBar);
customElements.define("top-bar", TopBar);
customElements.define("weather-widget", WidgetFinal);
customElements.define("day-temp", DayTemp);
customElements.define("categ-card", CategoryCard);
customElements.define("social-btn", SocialButton);
customElements.define("privacy-div", Privacy);
customElements.define("menu-left", MenuLeft);
customElements.define("orizontal-comp", OrizontalComponent);
customElements.define("orizontal-menu", OrizontalMenu);
customElements.define("news-comp", NewsComponent);
customElements.define("small-news", SmallNews);
customElements.define("breaking-news", BreakingNews);
customElements.define("source-news", GazetaComponent);
customElements.define("news-headline", NewsHeadline);
customElements.define("donate-popup", DonatePopUp);
customElements.define("custom-tag", Tag);
customElements.define("tag-container", TagContainer);
customElements.define("news-letter", NewsLetter);
customElements.define("popup-surs", PopupSource);
customElements.define("headline-popup", Popup);

// customElements.define("program-accordition", ProgramAcordeon);
